export const OPERATION_TYPES = {
  ADDITION: "ADDITION",
  SUBTRACTION: "SUBTRACTION",
  MULTIPLICATION: "MULTIPLICATION",
  DIVISION: "DIVISION",
  SQUARE_ROOT: "SQUARE_ROOT",
  RANDOM_STRING: "RANDOM_STRING",
};

export const OPERATION_TYPES_LABELS = {
  [OPERATION_TYPES.ADDITION]: "Addition",
  [OPERATION_TYPES.SUBTRACTION]: "Subtraction",
  [OPERATION_TYPES.MULTIPLICATION]: "Multiplication",
  [OPERATION_TYPES.DIVISION]: "Division",
  [OPERATION_TYPES.SQUARE_ROOT]: "Square Root",
  [OPERATION_TYPES.RANDOM_STRING]: "Random String",
};
